### ISSUE TITLE
Update Aave Data Sources for new asset

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/snapshotter-configs#4]
Aave has introduced a new asset that should be added to the AaveV3 use case config. This issue is for tracking since the last Aave update required a contract interface change as well.

**Comment by xadahiya** [comment]
Moving to current iteration. CC @Seth-Schmidt

**Comment by Seth-Schmidt** [comment]
The core and lite aave data source lists have been updated in the following commits:

https://github.com/PowerLoom/snapshotter-computes/commit/add235cda1dd9c44368c716bc2ba6d1b9937c6f6

https://github.com/PowerLoom/snapshotter-configs/commit/cbe7227ab9c8011143022e43a33b85c9476bd81c

**Comment by xadahiya** [comment]
Looks good! Let's deploy this
